remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Tom Macdonald
description: Welcome to my personal website, hosted on GitHub Pages! This site acts as a dynamic online resume, highlighting my skills, educational background, and professional journey.
Explore my projects, achievements, and experiences to get a comprehensive view of my expertise and passion for cybersecurity!
